name: workshop-pysal
channels:
  - conda-forge
dependencies:
  - python ==3.12
  - mamba
  - bokeh
  - pip
  - geopandas
  - folium
  - ipywidgets
  - jupyterlab
  - geodatasets
  - pysal
  - networkx
  - scikit-learn
  - seaborn
  - statsmodels
  - hvplot
  - holoviews
  - geoviews
  - watermark
  - rasterio
  - contextily
  - geosnap
